data:
  input:
    velib_dispo_data: "https://drive.google.com/file/d/1kBkBYm55NrNZ55fjD2G7jvdJqIz517Qm/view?usp=drive_link"
    velo_comptage_data: "https://drive.google.com/file/d/1IN7U_BkhrfPEfjCvD61sxVo_zMsKk6A9/view?usp=sharing"
    velo_comptage_refactored_data: "https://drive.google.com/file/d/1rxIYcPLq-mW6xl9gx-ktMy4EjDjjOrJz/view?usp=sharing"
    velo_comptage_ml_ready_data: "https://drive.google.com/file/d/1elLeEL-z4hCZZ4L4gkvFKoEUMlrwxl6w/view?usp=sharing"
