data:
  input:
    velib_dispo_data: "https://drive.google.com/file/d/1kBkBYm55NrNZ55fjD2G7jvdJqIz517Qm/view?usp=drive_link"
    velib_comptage_data: "https://drive.google.com/file/d/1IN7U_BkhrfPEfjCvD61sxVo_zMsKk6A9/view?usp=sharing"
    netflix_data: "https://drive.google.com/file/d/1eAbS-j4AtEP1ANeyULklF9IDT6zFKc2E/view?usp=drive_link"
    imdb_data: "https://drive.google.com/file/d/1v4COX6_Qnh-iQE0FJDPXmwKKz0O7XbyT/view?usp=drive_link"
    wines_data: "https://drive.google.com/file/d/1LoiJD7-lY7i2TE19yRP8DbeMJvnXQAw1/view?usp=drive_link"
    breast_cancer_data: "https://drive.google.com/file/d/1__VUBP-9eHYJJ9oaCRbDK4qeUc2-JZKq/view?usp=sharing"