[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mai25-bds-trafic-cycliste"
version = "0.3.0"
description = "bike trafic science project for MLE April 2025 promotion"
authors = [
    { name = "Rémy CANAL", email = "remy.canal@live.fr" },
    { name = "Elias DJOUADI", email = "dummy@mail.com" },
    { name = "Raphaël PARMENTIER", email = "dummy@mail.com" }
]
license = "MIT"
requires-python = ">=3.9,<3.13"

# NOTE: no direct dependencies — all handled through optional profiles
dependencies = []

[project.optional-dependencies]

py39 = [
    "numpy>=1.24,<1.26",
    "pandas>=1.5,<2.0",
    "scikit-learn==1.3.2",
    "matplotlib==3.7.0",
    "seaborn==0.12.2",
    "plotly==5.19.0",
    "bokeh==3.2.2",
    "scipy==1.10.1",
    "statsmodels==0.14.1",
    "mljar-scikit-plot==0.3.12",
    "xgboost==1.7.6",
    "imbalanced-learn==0.11.0",
    "tabulate==0.9.0",
    "scikit-optimize==0.10.1",
    "geopandas==0.13.2",
    "folium==0.15.1",
    "squarify==0.4.3",
    "missingno==0.5.2",
    "opencv-python==4.8.0.76",
    "pyyaml==6.0.1",
    "pyproj==3.5.0",
    "requests==2.31.0",
    "shap==0.48.0",
]

py310 = [
    "numpy>=1.24,<1.26",
    "pandas>=1.5,<2.0",
    "scikit-learn==1.3.2",
    "matplotlib==3.7.0",
    "seaborn==0.12.2",
    "plotly==5.19.0",
    "bokeh==3.2.2",
    "scipy==1.10.1",
    "statsmodels==0.14.1",
    "mljar-scikit-plot==0.3.12",
    "xgboost==1.7.6",
    "imbalanced-learn==0.11.0",
    "tabulate==0.9.0",
    "scikit-optimize==0.10.1",
    "geopandas==0.13.2",
    "folium==0.15.1",
    "squarify==0.4.3",
    "missingno==0.5.2",
    "opencv-python==4.8.0.76",
    "pyyaml==6.0.1",
    "pyproj==3.5.0",
    "requests==2.31.0",
    "shap==0.48.0",
]

py312 = [
    "numpy==2.2.6",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "matplotlib==3.10.3",
    "seaborn==0.13.2",
    "plotly==6.1.1",
    "bokeh==3.7.3",
    "scipy==1.15.3",
    "statsmodels==0.14.4",
    "mljar-scikit-plot==0.3.12",
    "xgboost==3.0.2",
    "imbalanced-learn==0.13.0",
    "tabulate==0.9.0",
    "scikit-optimize==0.10.2",
    "geopandas==1.1.0",
    "folium==0.20.0",
    "squarify==0.4.4",
    "missingno==0.5.2",
    "opencv-python==4.11.0.86",
    "pyyaml==6.0.2",
    "pyproj==3.7.1",
    "requests==2.32.4",
    "shap==0.48.0",
    "streamlit==1.46.1",
    "nltk==3.9.1",
    "wordcloud==1.9.4",
]

test = [
    "pytest==8.3.5",
    "coverage==7.8.2",
    "pytest-cov==6.1.1",
    "flake8==7.2.0",
    "nbstripout==0.8.1",
]

dev = [
    "notebook==7.4.3",
    "pre-commit==4.2.0",
    "ipywidgets==8.1.7",
    "jupysql==0.11.1",
    "sqlalchemy>=2.0",
    "sqlparse",
    "prettytable>=3.12.0",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Source = "https://github.com/zheddhe/mai25-bds-trafic-cycliste"

[tool.setuptools]
packages = { find = {} }
include-package-data = true

[tool.setuptools.package-data]
"smartcheck" = ["resources/*.yaml"]

[tool.pytest.ini_options]
addopts = "--cov --cov-config=.coveragerc --cov-report=html --cov-report=term"
testpaths = ["tests"]
pythonpath = ["."]
filterwarnings = [
    "ignore:The 'shapely.geos' module is deprecated"
]
