[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mai25-bds-trafic-cycliste"
version = "0.3.0"
description = "bike trafic science project for MLE April 2025 promotion"
authors = [
    { name = "Rémy CANAL", email = "remy.canal@live.fr" },
    { name = "Elias DJOUADI", email = "dummy@mail.com" },
    { name = "Raphaël PARMENTIER", email = "dummy@mail.com" }
]
license = "MIT"
requires-python = ">=3.9,<3.13"

# NOTE: no direct dependencies — all handled through optional profiles
dependencies = []

[project.optional-dependencies]

py312 = [
    "numpy>=1.26,<1.27",
    "pandas==2.2.3",
    "scikit-learn==1.5.0",
    "matplotlib==3.10.3",
    "seaborn==0.13.2",
    "plotly==6.1.1",
    "scipy==1.15.3",
    "statsmodels==0.14.4",
    "xgboost==3.0.2",
    "scikit-optimize==0.10.2",
    "geopandas==1.1.0",
    "folium==0.20.0",
    "squarify==0.4.4",
    "missingno==0.5.2",
    "pyyaml==6.0.2",
    "pyproj==3.7.1",
    "requests==2.32.4",
    "shap==0.48.0",
    "streamlit==1.46.1",
]

test = [
    "pytest==8.3.5",
    "coverage==7.8.2",
    "pytest-cov==6.1.1",
    "flake8==7.2.0",
    "nbstripout==0.8.1",
]

dev = [
    "notebook==7.4.3",
    "pre-commit==4.2.0",
    "ipywidgets==8.1.7",
    "jupysql==0.11.1",
]

dl = [
    "granite-tsfm==0.2.27",
    "netron==8.4.5",
    "tensorboard==2.20.0",
    "torchsummary==1.5.1",
    "captum==0.8.0",
    "transformers==4.53.2",
    "datasets==4.0.0",
    "evaluate==0.4.5",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Source = "https://github.com/zheddhe/mai25-bds-trafic-cycliste"

[tool.setuptools]
packages = { find = {} }
include-package-data = true

[tool.setuptools.package-data]
"smartcheck" = ["resources/*.yaml"]

[tool.pytest.ini_options]
addopts = "--cov --cov-config=.coveragerc --cov-report=html --cov-report=term"
testpaths = ["tests"]
pythonpath = ["."]
filterwarnings = [
    "ignore:The 'shapely.geos' module is deprecated"
]
