name: Workflow CI on feature branch

on:
  push: # Full Feedback on Push on feature branch
    branches-ignore:
      - main
      
jobs:
  ci-checks:
    name: 🔍 Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Check that notebooks are stripped
        run: |
          pip install nbstripout==0.8.1
          nbstripout --check --exit-zero-on-unchanged $(find . -name "*.ipynb")

      - name: Check code style with flake8
        run: |
          flake8 smartcheck tests

      - name: Run tests with coverage
        run: |
          pytest

      - name: Upload HTML coverage report locally
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov